# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#  This file is part of Wrye Bash.
#
#  Wrye Bash is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  Wrye Bash is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Wrye Bash; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#  Wrye Bash copyright (C) 2005-2009 Wrye, 2010-2015 Wrye Bash Team
#  https://github.com/wrye-bash
#
# =============================================================================
from collections import OrderedDict

Oblivion_Misc_bsa = OrderedDict([
    (u'menus', (
u'menus\\loading_bar_ingame_menu.xml', u'menus\\menu_labels.txt',
u'menus\\scroll_menu.xml', u'menus\\book_menu.xml',
u'menus\\persuasion_menu.xml', u'menus\\recharge_menu.xml',
u'menus\\birthsign_menu.xml', u'menus\\negotiate_menu.xml',
u'menus\\warning - changing these files.txt',
u'menus\\levelup_menu.xml', u'menus\\master_menu_file.txt',
u'menus\\sleep_wait_menu.xml', u'menus\\s.txt',
u'menus\\message_menu.xml', u'menus\\loading_ingame_menu.xml',
u'menus\\training_menu.xml', u'menus\\workbook.html',
u'menus\\loading_menu.xml', u'menus\\concat.bat',
u'menus\\ingredient_select_menu.xml', u'menus\\breath_meter_menu.xml',
u'menus\\quantity_menu.xml', u'menus\\repair_menu.xml',
u'menus\\container_menu.xml', u'menus\\vssver.scc',
u'menus\\strings.xml', u'menus\\class_menu.xml',
u'menus\\lockpick_menu.xml')),
    (u'fonts', (
u'fonts\\kingthings_regular.fnt',
u'fonts\\tahoma_bold_small_0_lod_a.tex',
u'fonts\\kingthings_shadowed_0_lod_a.tex', u'fonts\\daedric_font.fnt',
u'fonts\\handwritten_0_lod_a.tex', u'fonts\\handwritten.fnt',
u'fonts\\kingthings_regular_0_lod_a.tex',
u'fonts\\tahoma_bold_small.fnt', u'fonts\\kingthings_shadowed.fnt',
u'fonts\\daedric_font_0_lod_a.tex')),
    (u'menus\\prefabs', (
u'menus\\prefabs\\scroll_line.txt',
u'menus\\prefabs\\scroll_line.xml',
u'menus\\prefabs\\horiz_floating_scroll.xml',
u'menus\\prefabs\\xbox_floating_hint.xml',
u'menus\\prefabs\\page_tab.xml',
u'menus\\prefabs\\vertical_scroll.xml',
u'menus\\prefabs\\book_line.xml', u'menus\\prefabs\\fill_bar.xml',
u'menus\\prefabs\\button_short.xml',
u'menus\\prefabs\\button_floating.xml',
u'menus\\prefabs\\tile_button_over.xml',
u'menus\\prefabs\\vert_floating_scroll.xml',
u'menus\\prefabs\\button_floating_2.xml',
u'menus\\prefabs\\button_floating_3.xml',
u'menus\\prefabs\\button_xtralong.xml',
u'menus\\prefabs\\skill_item.xml',
u'menus\\prefabs\\generic_background.xml',
u'menus\\prefabs\\button_no_background.xml',
u'menus\\prefabs\\vssver.scc', u'menus\\prefabs\\tile_button.xml',
u'menus\\prefabs\\button_long.xml',
u'menus\\prefabs\\horizontal_scroll.xml',
u'menus\\prefabs\\focus_box.xml',
u'menus\\prefabs\\item_listing.xml')),
    (u'menus\\main', (
u'menus\\main\\copy of stats_menu.txt',
u'menus\\main\\player_model.xml',
u'menus\\main\\hud_main_menu.xml',
u'menus\\main\\hud_main_menu(2).xml',
u'menus\\main\\hud_info_menu.xml',
u'menus\\main\\quickkeys_menu.xml', u'menus\\main\\safe_zone.xml',
u'menus\\main\\hud_subtitle_menu.xml',
u'menus\\main\\magic_menu.xml', u'menus\\main\\vssver.scc',
u'menus\\main\\hud_reticle.xml',
u'menus\\main\\magic_popup_menu.xml',
u'menus\\main\\inventory_menu.xml', u'menus\\main\\map_menu.xml',
u'menus\\main\\stats_menu.xml')),
    (u'menus\\generic', (
u'menus\\generic\\test_menu.xml',
u'menus\\generic\\skill_perk.xml', u'menus\\generic\\vssver.scc',
u'menus\\generic\\quest_added.xml')),
    (u'menus\\options', (
u'menus\\options\\main_menu.xml',
u'menus\\options\\video_menu.xml',
u'menus\\options\\load_menu.xml',
u'menus\\options\\audio_menu.xml',
u'menus\\options\\xcontrols_menu.xml',
u'menus\\options\\credits_menu.xml',
u'menus\\options\\options_menu.xml',
u'menus\\options\\copy of main_menu.xml',
u'menus\\options\\vssver.scc',
u'menus\\options\\controls_menu.xml',
u'menus\\options\\save_menu.xml',
u'menus\\options\\downloads_menu.xml',
u'menus\\options\\pause_menu.xml',
u'menus\\options\\gameplay_menu.xml',
u'menus\\options\\video_display_menu.xml')),
    (u'menus\\chargen', (
u'menus\\chargen\\birthsign_menu.xml',
u'menus\\chargen\\skills_menu.xml',
u'menus\\chargen\\specilization_menu.xml',
u'menus\\chargen\\vssver.scc',
u'menus\\chargen\\attributes_menu.xml',
u'menus\\chargen\\class_menu.xml',
u'menus\\chargen\\race_sex_menu.xml')),
    (u'facegen', (u'facegen\\si.ctl',)),
    (u'menus\\message', (u'menus\\message\\message_menu.xml',)),
    (u'menus\\dialog', (
u'menus\\dialog\\sigilstone.xml',
u'menus\\dialog\\persuasion_menu.xml',
u'menus\\dialog\\dialog_menu.xml', u'menus\\dialog\\alchemy.xml',
u'menus\\dialog\\spell_purchase.xml',
u'menus\\dialog\\spellmaking.xml',
u'menus\\dialog\\enchantment.xml',
u'menus\\dialog\\enchantmentsetting_menu.xml',
u'menus\\dialog\\vssver.scc',
u'menus\\dialog\\texteditmenu.xml'))])

Skyrim_Interface_bsa = OrderedDict([
    (u'interface\\controls\\360', (
        u'interface\\controls\\360\\keyboard_english.txt',
        u'interface\\controls\\360\\gamepad.txt',
        u'interface\\controls\\360\\controlmap.txt')),
    (u'interface\\controls\\ps3', (
    u'interface\\controls\\ps3\\keyboard_english.txt',
    u'interface\\controls\\ps3\\gamepad.txt',
    u'interface\\controls\\ps3\\controlmap.txt')),
    (u'interface\\exported', (
        u'interface\\exported\\360_rb.png.dds',
        u'interface\\exported\\hudmenu.gfx',
        u'interface\\exported\\safezone.gfx',
        u'interface\\exported\\360_rs.png.dds',
        u'interface\\exported\\360_rt.png.dds',
        u'interface\\exported\\l-alt.png.dds',
        u'interface\\exported\\r-alt.png.dds',
        u'interface\\exported\\l-shift.png.dds',
        u'interface\\exported\\r-shift.png.dds',
        u'interface\\exported\\comma.png.dds',
        u'interface\\exported\\capslock.png.dds',
        u'interface\\exported\\right.png.dds',
        u'interface\\exported\\ps3_l3.png.dds',
        u'interface\\exported\\left.png.dds',
        u'interface\\exported\\period.png.dds',
        u'interface\\exported\\space.png.dds',
        u'interface\\exported\\ps3_lb.png.dds',
        u'interface\\exported\\ps3_r3.png.dds',
        u'interface\\exported\\mousemove.png.dds',
        u'interface\\exported\\360_ltrt.png.dds',
        u'interface\\exported\\equal.png.dds',
        u'interface\\exported\\ps3_ls.png.dds',
        u'interface\\exported\\ps3_lt.png.dds',
        u'interface\\exported\\ps3_rb.png.dds',
        u'interface\\exported\\hudmenu_i29e.dds',
        u'interface\\exported\\hudmenu_i2a1.dds',
        u'interface\\exported\\hudmenu_i2a7.dds',
        u'interface\\exported\\hudmenu_i2aa.dds',
        u'interface\\exported\\hudmenu_i2bb.dds',
        u'interface\\exported\\hudmenu_i2c1.dds',
        u'interface\\exported\\hudmenu_i2c7.dds',
        u'interface\\exported\\hudmenu_i2cd.dds',
        u'interface\\exported\\mouse.png.dds',
        u'interface\\exported\\ps3_rs.png.dds',
        u'interface\\exported\\ps3_rt.png.dds',
        u'interface\\exported\\tutorialmenu.gfx',
        u'interface\\exported\\tab.png.dds',
        u'interface\\exported\\bracketleft.png.dds',
        u'interface\\exported\\backspace.png.dds',
        u'interface\\exported\\360_a.png.dds',
        u'interface\\exported\\360_b.png.dds',
        u'interface\\exported\\ps3_ltrt.png.dds',
        u'interface\\exported\\textentry.gfx',
        u'interface\\exported\\enter.png.dds',
        u'interface\\exported\\quotesingle.png.dds',
        u'interface\\exported\\m1m2.png.dds',
        u'interface\\exported\\360_x.png.dds',
        u'interface\\exported\\360_y.png.dds',
        u'interface\\exported\\l-ctrl.png.dds',
        u'interface\\exported\\r-ctrl.png.dds',
        u'interface\\exported\\bracketright.png.dds',
        u'interface\\exported\\ps3_a.png.dds',
        u'interface\\exported\\ps3_b.png.dds',
        u'interface\\exported\\mouse1.png.dds',
        u'interface\\exported\\mouse2.png.dds',
        u'interface\\exported\\mouse3.png.dds',
        u'interface\\exported\\mouse4.png.dds',
        u'interface\\exported\\mouse5.png.dds',
        u'interface\\exported\\mouse6.png.dds',
        u'interface\\exported\\mouse7.png.dds',
        u'interface\\exported\\mouse8.png.dds',
        u'interface\\exported\\ps3_x.png.dds',
        u'interface\\exported\\ps3_y.png.dds',
        u'interface\\exported\\f10.png.dds',
        u'interface\\exported\\f11.png.dds', u'interface\\exported\\0.png.dds',
        u'interface\\exported\\1.png.dds', u'interface\\exported\\2.png.dds',
        u'interface\\exported\\3.png.dds', u'interface\\exported\\4.png.dds',
        u'interface\\exported\\5.png.dds', u'interface\\exported\\6.png.dds',
        u'interface\\exported\\7.png.dds', u'interface\\exported\\8.png.dds',
        u'interface\\exported\\9.png.dds', u'interface\\exported\\a.png.dds',
        u'interface\\exported\\b.png.dds', u'interface\\exported\\c.png.dds',
        u'interface\\exported\\d.png.dds', u'interface\\exported\\e.png.dds',
        u'interface\\exported\\f.png.dds', u'interface\\exported\\g.png.dds',
        u'interface\\exported\\h.png.dds', u'interface\\exported\\i.png.dds',
        u'interface\\exported\\j.png.dds', u'interface\\exported\\k.png.dds',
        u'interface\\exported\\l.png.dds', u'interface\\exported\\m.png.dds',
        u'interface\\exported\\n.png.dds', u'interface\\exported\\o.png.dds',
        u'interface\\exported\\p.png.dds', u'interface\\exported\\q.png.dds',
        u'interface\\exported\\r.png.dds', u'interface\\exported\\s.png.dds',
        u'interface\\exported\\t.png.dds', u'interface\\exported\\u.png.dds',
        u'interface\\exported\\v.png.dds', u'interface\\exported\\w.png.dds',
        u'interface\\exported\\x.png.dds', u'interface\\exported\\y.png.dds',
        u'interface\\exported\\z.png.dds', u'interface\\exported\\f12.png.dds',
        u'interface\\exported\\360_back.png.dds',
        u'interface\\exported\\ps3_lbrb.png.dds',
        u'interface\\exported\\diamondmarker.dds',
        u'interface\\exported\\hyphen.png.dds',
        u'interface\\exported\\esc.png.dds',
        u'interface\\exported\\f1.png.dds', u'interface\\exported\\f2.png.dds',
        u'interface\\exported\\f3.png.dds', u'interface\\exported\\f4.png.dds',
        u'interface\\exported\\f5.png.dds', u'interface\\exported\\f6.png.dds',
        u'interface\\exported\\f7.png.dds', u'interface\\exported\\f8.png.dds',
        u'interface\\exported\\f9.png.dds',
        u'interface\\exported\\tilde.png.dds',
        u'interface\\exported\\ps3_start.png.dds',
        u'interface\\exported\\slash.png.dds',
        u'interface\\exported\\semicolon.png.dds',
        u'interface\\exported\\up.png.dds',
        u'interface\\exported\\ps3_back.png.dds',
        u'interface\\exported\\360_l3.png.dds',
        u'interface\\exported\\down.png.dds',
        u'interface\\exported\\racesex_menu.gfx',
        u'interface\\exported\\360_lb.png.dds',
        u'interface\\exported\\360_r3.png.dds',
        u'interface\\exported\\backslash.png.dds',
        u'interface\\exported\\360_ls.png.dds',
        u'interface\\exported\\360_lt.png.dds',
        u'interface\\exported\\quest_journal.gfx',
        u'interface\\exported\\360_start.png.dds')),
    (u'strings', (
        u'strings\\skyrim_german.strings',
        u'strings\\skyrim_english.ilstrings',
        u'strings\\skyrim_italian.dlstrings',
        u'strings\\skyrim_english.strings',
        u'strings\\skyrim_spanish.ilstrings',
        u'strings\\skyrim_spanish.strings',
        u'strings\\skyrim_italian.ilstrings',
        u'strings\\skyrim_italian.strings',
        u'strings\\skyrim_french.dlstrings',
        u'strings\\skyrim_french.ilstrings',
        u'strings\\skyrim_german.dlstrings', u'strings\\skyrim_french.strings',
        u'strings\\skyrim_english.dlstrings',
        u'strings\\skyrim_german.ilstrings',
        u'strings\\skyrim_spanish.dlstrings')),
    (u'interface\\inventory components', (
        u'interface\\inventory components\\invertedinventorylists.swf',
        u'interface\\inventory components\\bottombar.swf',
        u'interface\\inventory components\\inventorylists.swf',
        u'interface\\inventory components\\itemcard.swf')),
    (u'interface', (
        u'interface\\widgetoverlay.swf', u'interface\\sleepwaitmenu.swf',
        u'interface\\containermenu.swf', u'interface\\fadermenu.swf',
        u'interface\\loadingmenu.swf', u'interface\\fonts_console.swf',
        u'interface\\giftmenu.swf', u'interface\\sharedcomponents.swf',
        u'interface\\cursormenu.swf', u'interface\\fonts_en.swf',
        u'interface\\tweenmenu.swf', u'interface\\startmenu.swf',
        u'interface\\messagebox.swf', u'interface\\bookmenu.swf',
        u'interface\\lockpickingmenu.swf', u'interface\\credits.txt',
        u'interface\\levelupmenu.swf', u'interface\\creditsmenu.swf',
        u'interface\\credits_french.txt', u'interface\\map.swf',
        u'interface\\book.swf', u'interface\\magicmenu.swf',
        u'interface\\favoritesmenu.swf', u'interface\\statsmenu.swf',
        u'interface\\dialoguemenu.swf', u'interface\\titles.swf',
        u'interface\\trainingmenu.swf', u'interface\\craftingmenu.swf',
        u'interface\\inventorymenu.swf', u'interface\\fontconfig.txt',
        u'interface\\bartermenu.swf', u'interface\\console.swf')),
    (u'interface\\controls\\pc', (
        u'interface\\controls\\pc\\keyboard_english.txt',
        u'interface\\controls\\pc\\keyboard_spanish.txt',
        u'interface\\controls\\pc\\keyboard_italian.txt',
        u'interface\\controls\\pc\\gamepad.txt',
        u'interface\\controls\\pc\\keyboard_french.txt',
        u'interface\\controls\\pc\\mouse.txt',
        u'interface\\controls\\pc\\keyboard_german.txt',
        u'interface\\controls\\pc\\controlmap.txt'))])

HeartOftheDead_Folder_Names=[
    ur"textures\menus\icons\hod\weapons\kagernac",
    ur"sound\voice\heartofthedead.esp\breton hod\f",
    ur"meshes\hod\clothing\lorkhans armor", ur"meshes\hod\clothing",
    ur"meshes\hod\creatures\ghost1", ur"meshes\hod\effects",
    ur"meshes\hod\gatekeeper", ur"textures\hod\ghosts",
    ur"meshes\hod\creatures\lichking",
    ur"meshes\hod\deadworld\monastary\living quarters",
    ur"meshes\hod\items\statues", ur"textures\hod\clothes\dogskull\f",
    ur"textures\hod\clothes\dogskull\m",
    ur"meshes\hod\creatures\skeleton2\idleanims", ur"textures\hod\crystalcave",
    ur"textures\hod\dwarven", ur"meshes\hod\shields",
    ur"meshes\hod\wknewruins\decorationsandstatues",
    ur"meshes\hod\wknewruins\hallsnarrow", ur"textures\hod\whitekingtextures",
    ur"meshes\hod\whitekingstatic", ur"meshes\hod\crystalcaves",
    ur"textures\hod\body\bw_bab", ur"textures\hod\body\bw_kat",
    ur"sound\voice\heartofthedead.esp\dark elf hod\m",
    ur"textures\characters\ren\ren_mysticelf_tt01\female",
    ur"textures\hod\druins\exterior", ur"textures\hod\dragon\particles\frost",
    ur"meshes\hod\clothing\deadworldarmor", ur"meshes\hod\crystalcaves\normal",
    ur"textures\hod\hair", ur"textures\hod\kagstools\kagernac",
    ur"meshes\hod\crystalcaves\normal\misc", ur"textures\hod\body\bw_imperial",
    ur"textures\hod\weapons\drblades", ur"video\hod",
    ur"meshes\hod\gatekeeper\specialanims", ur"textures\hod\objects",
    ur"textures\hod\lichking", ur"textures\hod\deadworld\bravil bridge",
    ur"textures\landscape\hod", ur"textures\characters\ren\ren_mysticelf\male",
    ur"textures\hod\objects\m8",
    ur"textures\characters\ren\ren_mysticelf_tt01",
    ur"meshes\hod\whitekingarmor\f", ur"meshes\hod\whitekingarmor\m",
    ur"meshes\hod\gatekeeper\idleanims",
    ur"sound\voice\heartofthedead.esp\nord\f",
    ur"sound\voice\heartofthedead.esp\nord\m",
    ur"meshes\hod\creatures\skeleton1\idleanims", ur"meshes\hod\dwarvencity",
    ur"meshes\hod\wknewruins", ur"textures\hod\deadworld\living quarters",
    ur"textures\hod\kagstools", ur"textures\hod\effects",
    ur"meshes\hod\clothing\katnewclothes1",
    ur"meshes\hod\clothing\katnewclothes2", ur"textures\characters\imperial",
    ur"meshes\hod\whitekingarmor",
    ur"sound\voice\heartofthedead.esp\imperial\f",
    ur"sound\voice\heartofthedead.esp\imperial\m",
    ur"textures\hod\deadworld\castle", ur"textures\hod\body\bw_darkelf",
    ur"meshes\hod\clothing\dogskull", ur"textures\menus\loading",
    ur"textures\menus\icons\hod",
    ur"sound\voice\heartofthedead.esp\redguard\f",
    ur"sound\voice\heartofthedead.esp\redguard\m",
    ur"textures\hod\clothes\fantasy\m", ur"textures\hod\shields",
    ur"textures\menus\icons\hod\weapons",
    ur"meshes\hod\wknewruins\ruinexteriors\brokentower",
    ur"textures\hod\water", ur"textures\hod\clothes\katnewclothes",
    ur"meshes\hod\creatures\zombie\specialanims", ur"textures\hod\wkcathedral",
    ur"sound\voice\heartofthedead.esp\high elf\f",
    ur"sound\voice\heartofthedead.esp\high elf\m",
    ur"meshes\hod\deadworld\monastary",
    ur"textures\characters\ren\ren_mysticelf_tt01\male",
    ur"meshes\hod\wknewruins\ruinexteriors",
    ur"sound\voice\heartofthedead.esp\high elf hod\m",
    ur"textures\hod\deadworld", ur"meshes\hod\kagstools",
    ur"meshes\hod\wkcathedral", ur"meshes\hod\creatures\zombie",
    ur"meshes\hod\creatures\dragon", ur"meshes\hod\wknewruins\assortedroots",
    ur"meshes\hod\blackcaves\pit", ur"meshes\hod\dwarvencity\traps",
    ur"textures\hod\deadworld\living quarters\furniture",
    ur"textures\hod\zombie", ur"meshes\hod\creatures\dragon\idleanims",
    ur"textures\hod\deadworld\ar", ur"textures\hod\weapons\deadworldweapons",
    ur"textures\hod\dragon", ur"textures\hod\druins", ur"textures\hod\statues",
    ur"sound\voice\heartofthedead.esp\argonian\f",
    ur"sound\voice\heartofthedead.esp\argonian\m",
    ur"textures\characters\ren\ren_mysticelf",
    ur"textures\menus\icons\hod\armor\shields",
    ur"meshes\hod\creatures\ghost1\idleanims",
    ur"textures\characters\ren\eyes", ur"textures\characters\ren\hair",
    ur"meshes\hod\blackcaves\chasm",
    ur"textures\menus\icons\hod\armor\dogskull",
    ur"meshes\characters\ren\eyes", ur"meshes\characters\ren\hair",
    ur"meshes\characters\ren\head", ur"textures\hod\dwarven\gems",
    ur"meshes\hod\blackcaves\rocks", ur"textures\hod\gatekeeper",
    ur"meshes\hod\weapons", ur"meshes\hod\wknewruins\pits",
    ur"textures\hod\clothes\deadworldarmor", ur"meshes\hod\hair",
    ur"textures\hod\clothes\lorkhan armor", ur"textures\hod\crystalcave\rooms",
    ur"textures\hod\fadeout", ur"textures\hod\weapons\staffs",
    ur"textures\menus\icons\hod\armor", ur"meshes\hod\deadworld",
    ur"textures\hod\body\bw_mystic\male", ur"textures\hod\body\ff_imperial",
    ur"meshes\hod\objects\finalhousetapestries",
    ur"textures\hod\deadworld\chorrol",
    ur"sound\voice\heartofthedead.esp\argonian hod\m",
    ur"textures\menus\book\hod",
    ur"textures\hod\weapons\nico's dreadweave bow",
    ur"meshes\hod\crystalcaves\crystal", ur"textures\hod\body\bw_darkelf\male",
    ur"meshes\hod\wknewruins\hallswide", ur"textures\hod\skeleton",
    ur"meshes\hod\caves", ur"meshes\hod\wkwalls",
    ur"meshes\hod\weapons\deadworldweapons", ur"meshes\hod\items",
    ur"meshes\hod\weapons\shdw",
    ur"textures\characters\ren\ren_mysticelf\female",
    ur"textures\hod\whitekingtextures\f", ur"textures\hod\whitekingtextures\m",
    ur"textures\hod\clothes\assassin_armor_elite",
    ur"textures\hod\clothes\katnewclothes\skirt_short_02",
    ur"textures\hod\body\bw_mystic\female", ur"textures\hod\body\bab_imperial",
    ur"textures\hod\deadsky", ur"textures\hod\body\ff_ren",
    ur"textures\menus\icons\hod\weapons\shdw",
    ur"textures\hod\objects\finalhousetapestries", ur"meshes\hod\dwarven",
    ur"meshes\hod\clothing\dogskull\f", ur"meshes\hod\clothing\dogskull\m",
    ur"meshes\hod\druins\blocksandrubble", ur"textures\hod\objects\finalbed",
    ur"meshes\hod\dwarvencity\mineshaft", ur"textures\hod\ice",
    ur"textures\hod\clothes", ur"meshes\hod\blackcaves",
    ur"sound\voice\heartofthedead.esp\wood elf hod\m",
    ur"sound\voice\heartofthedead.esp\mystic elf\f",
    ur"sound\voice\heartofthedead.esp\mystic elf\m",
    ur"meshes\hod\creatures\lichking\idleanims",
    ur"meshes\hod\blackcaves\narrow", ur"meshes\hod\blackcaves\big room",
    ur"meshes\hod\crystalcaves\normal\withcrystal",
    ur"meshes\hod\clothing\mystic armor\f",
    ur"meshes\hod\clothing\mystic armor\m", ur"meshes\hod\dragonruins",
    ur"meshes\characters\_male\idleanims\hod",
    ur"meshes\hod\creatures\skeleton1", ur"meshes\hod\creatures\skeleton2",
    ur"textures\hod\weapons\shdw", ur"music\hod", ur"sound\fx\hod",
    ur"meshes\hod\blackcaves\wide hall", ur"meshes\hod\blackcaves\small room",
    ur"meshes\hod\objects", ur"meshes\hod\druins",
    ur"textures\hod\weapons\dreadweave weapons", ur"textures\hod\wkdoor",
    ur"meshes\hod\wknewruins\rooms", ur"textures\hod\deadworld\leyawiin",
    ur"meshes\hod\wknewruins\traps", ur"textures\hod\wkroots",
    ur"textures\hod\body\bw_mystic", ur"meshes\hod\creatures\zombie\idleanims",
    ur"textures\hod\wkwalls", ur"meshes\hod\editedroottiles",
]

MidasSpells = [
    ur"textures\weapons", ur"textures\menus\icons\clutter\gems",
    ur"textures\clutter", ur"meshes\creatures\boar", ur"meshes\creatures\deer",
    ur"meshes\creatures\lich", ur"meshes\creatures\ogre",
    ur"meshes\creatures\midasmechwalker", ur"meshes\creatures\midasumberlarva",
    ur"sound\voice\midasspells.esp\driad\f", ur"textures\dungeons\misc",
    ur"sound\fx\npc\midasbeholder\aware",
    ur"textures\creatures\midascreatures", ur"meshes\creatures\midascent",
    ur"meshes\creatures\midaswolf", ur"meshes\creatures\goblin",
    ur"sound\fx\npc\midasbeholder\injured", ur"textures\plants",
    ur"meshes\creatures\midasprojectile", ur"textures\python",
    ur"meshes\creatures\midasumberhulk\idleanims", ur"textures\armor\glass\f",
    ur"meshes\creatures\midasairwisp", ur"meshes\creatures\dog",
    ur"meshes\magiceffects", ur"meshes\creatures\mudcrab",
    ur"meshes\creatures\midasbalrog\idleanims",
    ur"meshes\creatures\midastiger\idleanims",
    ur"meshes\creatures\midasbeholder",
    ur"meshes\creatures\midasairwisp\idleanims",
    ur"meshes\creatures\midascent\idleanims", ur"meshes\weapons\midas",
    ur"textures\creatures\goblin", ur"meshes\creatures\midasumberhulk",
    ur"textures\characters\midaswreyth",
    ur"meshes\creatures\midasfiresprite\idleanims", ur"textures\magic",
    ur"meshes\characters\midaswreyth",
    ur"meshes\creatures\midaswolf\idleanims", ur"textures\clothes\monkwhite",
    ur"textures\magic\midasnuke", ur"meshes\architecture\midasastralplane",
    ur"meshes\creatures\midascoinseeker", ur"textures\menus\icons",
    ur"textures\midasarchitecture", ur"meshes\creatures\midasscorpion",
    ur"meshes\python", ur"meshes\creatures\midasatronach\idleanims",
    ur"meshes\creatures\midasjelly", ur"sound\fx\magic",
    ur"meshes\characters\_male\idleanims", ur"meshes\creatures\midasswarm",
    ur"meshes\creatures\midastiger", ur"textures\menus\book",
    ur"meshes\creatures\midaswings", ur"textures\creatures\clannfear",
    ur"meshes\clutter", ur"meshes\creatures\clannfear",
    ur"textures\characters\ren\hair",
    ur"textures\creatures\midascreatures\midashair",
    ur"meshes\creatures\zombie", ur"meshes\creatures\midasbeholder\idleanims",
    ur"textures\creatures\xivilai", ur"textures\armor\mythicdawn",
    ur"meshes\armor\midasarmor", ur"music\special",
    ur"meshes\creatures\spriggan", ur"textures\landscape",
    ur"textures\fire\midasholyfire",
    ur"sound\voice\midasspells.esp\imperial\m",
    ur"meshes\creatures\midaswings\idleanims",
    ur"sound\fx\npc\midasbeholder\idle", ur"meshes\creatures\flameatronach",
    ur"meshes\creatures\midasscorpion\idleanims",
    ur"textures\creatures\zombie", ur"meshes\creatures\midasfiresprite",
    ur"textures\clutter\potions", ur"meshes\creatures\midasbalrog",
    ur"sound\voice\midasspells.esp\high elf\m",
    ur"meshes\creatures\frostatronach", ur"textures\creatures\troll",
    ur"meshes\creatures\scamp", ur"meshes\creatures\troll",
    ur"textures\characters\eyes", ur"sound\fx\npc\midasbeholder\attack",
    ur"sound\voice\midasspells.esp\argonian\m",
    ur"meshes\creatures\midastentacle", ur"meshes\creatures\skeleton",
    ur"meshes\creatures\slaughterfish", ur"meshes\creatures\midascarpet",
    ur"meshes\creatures\daedroth", ur"meshes\creatures\xivilai",
    ur"meshes\creatures\midascarpet\idleanims",
    ur"meshes\creatures\midasatronach", ur"textures\clothes\robemagearch",
]

SkyrimSETextures8 = OrderedDict([
    (u'textures\\_byoh\\furniture', (
        u'textures\\_byoh\\furniture\\craftingtable01.dds',
        u'textures\\_byoh\\furniture\\draftingtable01.dds',
        u'textures\\_byoh\\furniture\\craftingtable01_n.dds',
        u'textures\\_byoh\\furniture\\draftingtable01_n.dds',
        u'textures\\_byoh\\furniture\\plans01.dds',
        u'textures\\_byoh\\furniture\\oven01_g.dds',
        u'textures\\_byoh\\furniture\\oven01_n.dds',
        u'textures\\_byoh\\furniture\\oven01.dds',
        u'textures\\_byoh\\furniture\\plans01_n.dds')),
    (u'textures\\_byoh\\plants', (
        u'textures\\_byoh\\plants\\hawksnest01.dds',)),
    (u'textures\\_byoh\\clutter\\resources', (
        u'textures\\_byoh\\clutter\\resources\\claybrick01_n.dds',
        u'textures\\_byoh\\clutter\\resources\\orestone01.dds',
        u'textures\\_byoh\\clutter\\resources\\horn01_bl.dds',
        u'textures\\_byoh\\clutter\\resources\\stonequarry01.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit01_n.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit02_n.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit03_n.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit04_n.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit05_n.dds',
        u'textures\\_byoh\\clutter\\resources\\glass01_n.dds',
        u'textures\\_byoh\\clutter\\resources\\horn01.dds',
        u'textures\\_byoh\\clutter\\resources\\claybrick01.dds',
        u'textures\\_byoh\\clutter\\resources\\stonequarry01_n.dds',
        u'textures\\_byoh\\clutter\\resources\\horn01_n.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit01.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit02.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit03.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit04.dds',
        u'textures\\_byoh\\clutter\\resources\\claydeposit05.dds')),
    (u'textures\\_byoh\\clothes\\childrenclothesvariants\\m', (
        u'textures\\_byoh\\clothes\\childrenclothesvariants\\m\\childrenclothes04.dds', u'textures\\_byoh\\clothes\\childrenclothesvariants\\m\\childrenclothes05.dds')),
    (u'textures\\_byoh\\clutter\\ingredients', (
        u'textures\\_byoh\\clutter\\ingredients\\salmonroe01_n.dds',
        u'textures\\_byoh\\clutter\\ingredients\\salmonroe01_bl.dds',
        u'textures\\_byoh\\clutter\\ingredients\\salmonroe01.dds')),
    (u'textures\\_byoh\\clutter\\house crafting', (
        u'textures\\_byoh\\clutter\\house crafting\\lock01_n.dds',
        u'textures\\_byoh\\clutter\\house crafting\\nail01_n.dds',
        u'textures\\_byoh\\clutter\\house crafting\\nail01.dds',
        u'textures\\_byoh\\clutter\\house crafting\\hinge01_n.dds',
        u'textures\\_byoh\\clutter\\house crafting\\lock01.dds',
        u'textures\\_byoh\\clutter\\house crafting\\ironfittings01.dds',
        u'textures\\_byoh\\clutter\\house crafting\\ironfittings01_n.dds',
        u'textures\\_byoh\\clutter\\house crafting\\hinge01.dds')), (
    u'textures\\_byoh\\clutter', (
    u'textures\\_byoh\\clutter\\_byohstraw01.dds',
    u'textures\\_byoh\\clutter\\breadpeel01.dds',
    u'textures\\_byoh\\clutter\\drawknife_n.dds',
    u'textures\\_byoh\\clutter\\breadpeel01_n.dds',
    u'textures\\_byoh\\clutter\\_byohstraw01_n.dds',
    u'textures\\_byoh\\clutter\\drawknife.dds')), (
    u'textures\\_byoh\\clutter\\doll', (
    u'textures\\_byoh\\clutter\\doll\\doll_d.dds',
    u'textures\\_byoh\\clutter\\doll\\doll_n.dds')), (
    u'textures\\_byoh\\clutter\\food', (
    u'textures\\_byoh\\clutter\\food\\cabbagepotatosoup01.dds',
    u'textures\\_byoh\\clutter\\food\\potatosoup01_n.dds',
    u'textures\\_byoh\\clutter\\food\\mudcrablegs01_n.dds',
    u'textures\\_byoh\\clutter\\food\\applecabbagestew01_n.dds',
    u'textures\\_byoh\\clutter\\food\\garlicbread01_n.dds',
    u'textures\\_byoh\\clutter\\food\\tomatosoup01_n.dds',
    u'textures\\_byoh\\clutter\\food\\tartsnowberry01.dds',
    u'textures\\_byoh\\clutter\\food\\tart01_n.dds',
    u'textures\\_byoh\\clutter\\food\\venisonstew01.dds',
    u'textures\\_byoh\\clutter\\food\\horkerstew01_n.dds',
    u'textures\\_byoh\\clutter\\food\\tomatosoup01.dds',
    u'textures\\_byoh\\clutter\\food\\horkerstew01.dds',
    u'textures\\_byoh\\clutter\\food\\braidedbread01_n.dds',
    u'textures\\_byoh\\clutter\\food\\dumpling01.dds',
    u'textures\\_byoh\\clutter\\food\\potatobread01.dds',
    u'textures\\_byoh\\clutter\\food\\tartjazbay01.dds',
    u'textures\\_byoh\\clutter\\food\\elseweyrfondue01_n.dds',
    u'textures\\_byoh\\clutter\\food\\cookedmudcrablegs01.dds',
    u'textures\\_byoh\\clutter\\food\\applecabbagestew01.dds',
    u'textures\\_byoh\\clutter\\food\\dumpling01_n.dds',
    u'textures\\_byoh\\clutter\\food\\cookedsalmonsteak02.dds',
    u'textures\\_byoh\\clutter\\food\\clamchowder01_n.dds',
    u'textures\\_byoh\\clutter\\food\\milkjug01_n.dds',
    u'textures\\_byoh\\clutter\\food\\vegetablesoup01.dds',
    u'textures\\_byoh\\clutter\\food\\floursack01.dds',
    u'textures\\_byoh\\clutter\\food\\mudcrablegs01.dds',
    u'textures\\_byoh\\clutter\\food\\potatosoup01.dds',
    u'textures\\_byoh\\clutter\\food\\potatobread01_n.dds',
    u'textures\\_byoh\\clutter\\food\\braidedbread01.dds',
    u'textures\\_byoh\\clutter\\food\\beefstew01_n.dds',
    u'textures\\_byoh\\clutter\\food\\butter01_n.dds',
    u'textures\\_byoh\\clutter\\food\\elseweyrfondue01.dds',
    u'textures\\_byoh\\clutter\\food\\vegetablesoup01_n.dds',
    u'textures\\_byoh\\clutter\\food\\garlicbread01.dds',
    u'textures\\_byoh\\clutter\\food\\clamchowder01.dds',
    u'textures\\_byoh\\clutter\\food\\butter01.dds',
    u'textures\\_byoh\\clutter\\food\\tartjuniper01.dds',
    u'textures\\_byoh\\clutter\\food\\milkjug01.dds',
    u'textures\\_byoh\\clutter\\food\\beefstew01.dds')), (
    u'textures\\_byoh\\clutter\\wine', (
    u'textures\\_byoh\\clutter\\wine\\winebottles02.dds',
    u'textures\\_byoh\\clutter\\wine\\winebottles02_bl.dds',
    u'textures\\_byoh\\clutter\\wine\\winebottles02_n.dds')), (
    u'textures\\_byoh\\weapons\\woodensword', (
    u'textures\\_byoh\\weapons\\woodensword\\woodensword_d.dds',
    u'textures\\_byoh\\weapons\\woodensword\\woodensword_n.dds'))])
